version: '2'

services:

  peer:
    image: rakutenrbl/multichain-peer:latest
    volumes:
      - multichain_peer_data:/root
    ports:
      - "9578:9578"
    environment:
      CHAIN: test-chain

volumes:
  multichain_peer_data:

