version: '2'

services:

  peer:
    image: rakutenrbl/multichain-peer:latest
    volumes:
      - multichain_peer_data:/root
    ports:
      - "7801:7801"
      - "7802:7802"
    environment:
      CHAIN: test-chain

volumes:
  multichain_peer_data:

